# Generated by Django 5.2.7 on 2025-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('KHALTI', 'Khalti'), ('COD', 'Cash on Delivery')], default='KHALTI', max_length=10),
        ),
    ]
